### ISSUE TITLE
No LICENSE for github.com/shogo82148/go-shuffle?

### ISSUE THREAD

**Issue by anthonyfok** [shogo82148/go-shuffle#3]
No LICENSE or LICENSE.md file is included for github.com/shogo82148/go-shuffle,
nor is there any indication of github.com/shogo82148/go-shuffle's license anywhere in README.md or in the source code.

This prevents github.com/shogo82148/go-shuffle from being packaged by Linux distributions like Debian or Fedora.

Thank you for your kind consideration.

**Comment by shogo82148** [comment]
Fixed by #4 .
Thank you!
